archerysec/archerysec

README.md

`$ cd archerysec` without leading slash

Fixed change directory

---

README.md

ZAP settings location has changed. I've updated the README.md to point to correct location. I also added some clarification on what the "zap.sh" and "zap.bat" files are and where to find them.

Update ZAP Setup Instructions

---

Dashboard/templates/dashboard_sidebar.html
archerysecurity/static/css/archery-style.css
networkscanners/templates/ipscan.html
requirements.txt
tools/models.py
tools/nmap_vulners/nmap_vulners_scan.py
tools/nmap_vulners/nmap_vulners_view.py
tools/nmap_vulners/vulners.nse
tools/templates/nmap_vulners_list.html
tools/templates/nmap_vulners_port_list.html
tools/urls.py
tools/views.py
webscanners/templates/sidebar.html
webscanners/templates/table_sidebar.html

This pull request proposes another type of nmap scan using the Vulners dot com API.
- The used NSE script is the lates one from the official repo (https://github.com/vulnersCom/nmap-vulners). It is open and free to use, so it suites perfectly the whole ArcherySec idea.
- In order not to be intrusive I have implemented everything in a most independent way: most of the changes are in separate files, the main project files are untouched.
- Following the general idea of being non-disturbing I have added a separate table (yet with a foreign key to an old one)
NB: This scan type does make many requests to a 3rd party resource (vulners dot com), yet it does include a disclaimer and does not collect much information about the users, so there is no concern of privacy violation.

Propose another scan type to the project (nmap+vulners API)

---

requirements.txt
webscanners/models.py
webscanners/templates/cookies_list.html
webscanners/templates/excludedurl_list.html
webscanners/templates/webscanner.html
webscanners/urls.py
webscanners/web_views.py

+ Added functionality that allow to delete already stored cookies from cookies list.
+ Also added functionality that allow to delete excluded URL from  the list.

#36 Delete Cookies from cookies list.

---

Dashboard/templates/dashboard.html
Dashboard/templates/network_scan_dashboard.html
Dashboard/templates/web_scan_dashboard.html
Dashboard/views.py

#51 Vulnerability Status: Close & Open

---

README.md
systemd/system/archery.service
systemd/system/burp-api.service
systemd/system/owasp-zap.service

Based on our discussion for the OpenVAS connection refused issue, here is my PR
I also added in it some systemd files that are convenient to run Archery and its dependencies

Update README (installation part) and adding systemd service files

---

archerysecurity/settings.py

Default TZ should be UTC

---

README.md
archerysecurity/local_settings.sample.py
archerysecurity/management/commands/initadmin.py
archerysecurity/management/initadmin.py
docker_run.sh
docs/install.md
install.sh

what i did:
* include command to auto create a superuser on first install. does nothing if there is 1 or more users already on the db
* remove makemigration command which are not necessary any more after adding them to version control

Auto create superuser

---

archerysecurity/local_settings.sample.py
archerysecurity/settings.py
archerysecurity/urls.py
requirements.txt

what i did:
* install and configure the django debug toolbar for debugging and development of archerysec
* default DEBUG setting to False and set to True on local_settings file if needed

Setup django debug toolbar

---

archerysecurity/local_settings.sample.py
archerysecurity/settings.py
archerysecurity/urls.py
requirements.txt

Reverts archerysec/archerysec#93

Revert "Setup django debug toolbar"

---

archerysecurity/settings/development.py
docker-compose.yml

what i did:
* add mailhog container and configure archerysec for using it as a dev email viewer
* remove unused volume

Implement mailhog for development env

---

Dockerfile

what i did: 
* create and archerysec user
* run everything using this user
this change can be tested out using this image: `httpdss/archerysec:non-root-user`
with this changes, "Fix security issues in docker image" #20 should be closed.

Non root user for dockerfile

---

README.md

Your tool/software has been inventoried on [*Rawsec's CyberSecurity Inventory*](https://inventory.rawsec.ml/tools.html#Archery).
An inventory of tools and resources about CyberSecurity. This inventory aims to help people to find everything related to CyberSecurity.
+ **Open source**: Every information is available and up to date. If an information is missing or deprecated, you are invited to (help us).
+ **Practical**: Content is categorized and table formatted, allowing to search, browse, sort and filter.
+ **Fast**: Using static and client side technologies resulting in fast browsing.
+ Rich tables: search, sort, browse, filter, clear
+ Fancy informational popups
+ Badges / Shields
+ Static API
+ Twitter bot
More details about features [here](https://inventory.rawsec.ml/features.html). …

Inventory notification

---

PyArachniapi.py

Simple authentication added to library

Simple authentication added to library

---

docker-files/init.sh
networkscanners/views.py
scanners/scanner_plugin/network_scanner/openvas_plugin.py
scanners/scanner_plugin/web_scanner/zap_plugin.py
webscanners/web_views.py
webscanners/zapscanner/views.py

This merge request fixes scheduled scans with worker and openvas/zap scanners. Also it fixes scheduled scan deleting

Fix scheduled scans with zap/openvas

---

scanners/scanner_parser/staticscanner_parser/trivy_json_report_parser.py

Trivy reports can contain the following:
`"Type": "gobinary",
"Vulnerabilities": null`
which wasn't handled by the previous code and the reports were not processed. This PR should resolve that and worked in my testing.

Null on Trivy reports

---

templates/networkscanners/scans/vuln_details.html
templates/pentest/manual_vuln_data.html
templates/staticscanners/scans/vuln_details.html
templates/webscanners/scans/vuln_details.html

#513  - fixed the security concern due to autoescape has safe filters applied.

Removed safe filters From auto escape html due to security concern

---

scanners/scanner_parser/web_scanner/zap_xml_parser.py

Fixed ZAP v2.11.1 xml report upload

---

archeryapi/views.py
archerysecurity/management/commands/initadmin.py
common/views.py
pentest/views.py
tools/nmap_vulners/nmap_vulners_scan.py

sec code enhancement

---

templates/users/add_user.html

dropdown was not working in add user form

fixed dropdown issue

---

archeryapi/views.py

fix-api-upload-scan-error
